c_compiler:
- gcc
c_compiler_version:
- '12'
cdt_name:
- cos7
cdt_arch:
- armv7l
channel_sources:
- conda-forge
channel_targets:
- conda-forge main
cuda_compiler:
- None
cuda_compiler_version:
- None
cudnn:
- '8'
cxx_compiler:
- gxx
cxx_compiler_version:
- '12'
docker_image:
- quay.io/condaforge/linux-anvil-cuda:11.2
numpy:
- '1.24'
- '1.24'
- '1.24'
- '1.24'
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
python:
- 3.11.* *_cpython
- 3.10.* *_cpython
- 3.9.* *_cpython
- 3.8.* *_cpython
suffix:
- ''
target_platform:
- linux-armv7l
zip_keys:
- - c_compiler_version
  - cxx_compiler_version
  - cudnn
  - cuda_compiler
  - cuda_compiler_version
  - cdt_name
  - docker_image
- - python
  - numpy
zlib:
- '1.2'
